// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CoreLayer.Entities
{
    public partial class Colors
    {
        public Colors()
        {
            Products = new HashSet<Product>();
        }

        [Key]
        public int Id { get; set; }
        //[Required]
        [StringLength(100)]
        public string Color { get; set; }

        [InverseProperty("ProductColor")]
        public virtual ICollection<Product> Products { get; set; }
    }
}